<a href="https://colab.research.google.com/github/Lukasz2107/learning/blob/main/numpy_tutorials/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#https://www.w3resource.com/python-exercises/numpy/basic/index.php

In [1]:
import numpy as np

In [4]:
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [10]:
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [20]:
array1 = np.array([1,2,3,4,5])
print(np.all(array1))

array2 = np.array([0,1,2,3,4,5])
print(np.all(array2))

True
False


In [28]:
array1 = np.array([0,0,0,0])
print(np.any(array1))

array2 = np.array([0,0,1])
print(np.any(array2))

False
True


In [31]:
array1 = np.array([0,1,2, np.nan, True, np.inf])
print(np.isfinite(array1))


[ True  True  True False  True False]


In [35]:
array1 = np.array([np.inf, 0])

print(np.isinf(array1))

[ True False]


In [38]:
array1 = np.array([np.nan, 4, 5])

print(np.isnan(array1))

[ True False False]


In [45]:
array1 = np.array([1,2,3,4,5, 1+1j])
num = 5
print(np.iscomplex(array1))
print(np.isreal(array1))
print(np.isscalar(array1))
print(np.isscalar(num))

[False False False False False  True]
[ True  True  True  True  True False]
False
True


In [56]:
print(np.allclose([2.0001, 0.0001], [2.0001, 0.0001]))

True


In [62]:
array1 = np.array([-1, 1,2,3,4])
array2 = np.array([0,1,2,3,5])

print(np.greater(array2, array1))
print(np.greater_equal(array2, array1))
print(np.less(array2, array1))
print(np.less_equal(array2, array1))

[ True False False False  True]
[ True  True  True  True  True]
[False False False False False]
[False  True  True  True False]


In [90]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.00001])

print(np.equal(x, y))
print(np.allclose(x,y, 0.01))


[ True  True  True  True  True  True  True  True  True False]
True


In [98]:
x = np.array([1, 7, 13, 105])
print((x.size * x.itemsize), 'bytes')

32 bytes


In [102]:
np.zeros(10)
np.ones(10)
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [109]:
np.arange(30, 71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [110]:
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [111]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
np.random.normal(0,1)

[0.22190661085121757,
 0.22190661085121757,
 0.22190661085121757,
 0.22190661085121757,
 0.22190661085121757,
 0.22190661085121757,
 0.22190661085121757,
 0.22190661085121757,
 0.22190661085121757,
 0.22190661085121757]

In [117]:
np.random.normal(0,1,15)

array([-0.52132338, -1.08642903, -1.03437034, -0.94261268,  0.1011446 ,
        0.75752478, -0.06603319,  0.05942514,  1.26974815,  0.01917035,
        0.24908204, -0.0276048 ,  0.37039235, -0.70639423, -0.10795243])

In [126]:
x = np.arange(15, 56)
print(x[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [150]:
x = np.arange(1, 13).reshape((3, 4))


for i in list(x):
  for j in i:
    print(j, end=" ")
print()

for i in np.nditer(x):
  print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 
1 2 3 4 5 6 7 8 9 10 11 12 

In [156]:
a = np.linspace(5, 50, 10)
a

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [162]:
b = np.arange(21)
b[9:16] *= -1
print(b)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [171]:
c = np.random.randint(0, 11, 5)
c

array([ 6, 10,  4,  5,  5])

In [172]:
a = np.array([1,2,3,4])
b = np.array([5,4,3,1])

a*b

array([5, 8, 9, 4])

In [175]:
c = np.arange(10, 22).reshape((3,4))
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [178]:
a = np.array([[1,2,3,4], [5,6,7,8]])
np.shape(a)

(2, 4)

In [184]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [195]:
b = np.ones((10,10))
b[1:-1, 1:-1] = 0
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [201]:
c = np.diag([1, 2, 3, 4, 5])
c

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [226]:
d = np.zeros((4, 4))
d[::2, 1::2] = 1    #first index is the row, second is the col
d[1::2, ::2] = 1
d

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])